// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZoUbiyCq_Py5L9pCe1TxBziD8KrtUwN0',
    appId: '1:699646362176:web:365cdbc8b47cc8038615a5',
    messagingSenderId: '699646362176',
    projectId: 'christmasy-d964e',
    authDomain: 'christmasy-d964e.firebaseapp.com',
    storageBucket: 'christmasy-d964e.firebasestorage.app',
    measurementId: 'G-8WYDRXYV8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEC2GZPMCFl6dBEWNwib0rwZ0-6LW6MAg',
    appId: '1:699646362176:android:a16520fec2eb86ea8615a5',
    messagingSenderId: '699646362176',
    projectId: 'christmasy-d964e',
    storageBucket: 'christmasy-d964e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6MkTv6zwpC9hSoKHXCZjvgpPjF0oLsh0',
    appId: '1:699646362176:ios:5162961bce11499e8615a5',
    messagingSenderId: '699646362176',
    projectId: 'christmasy-d964e',
    storageBucket: 'christmasy-d964e.firebasestorage.app',
    iosClientId: '699646362176-oppsru3hi0n9vfvhh6ge5os4m1m22scm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6MkTv6zwpC9hSoKHXCZjvgpPjF0oLsh0',
    appId: '1:699646362176:ios:5162961bce11499e8615a5',
    messagingSenderId: '699646362176',
    projectId: 'christmasy-d964e',
    storageBucket: 'christmasy-d964e.firebasestorage.app',
    iosClientId: '699646362176-oppsru3hi0n9vfvhh6ge5os4m1m22scm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZoUbiyCq_Py5L9pCe1TxBziD8KrtUwN0',
    appId: '1:699646362176:web:69938424bfda07b38615a5',
    messagingSenderId: '699646362176',
    projectId: 'christmasy-d964e',
    authDomain: 'christmasy-d964e.firebaseapp.com',
    storageBucket: 'christmasy-d964e.firebasestorage.app',
    measurementId: 'G-F17CB5CBC0',
  );
}
