// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZLXwRpGaMYM65oj726PhO1duyFdB8r0',
    appId: '1:159024373084:web:25474fe7e18d4d49113599',
    messagingSenderId: '159024373084',
    projectId: 'moappfinal-98952',
    authDomain: 'moappfinal-98952.firebaseapp.com',
    storageBucket: 'moappfinal-98952.firebasestorage.app',
    measurementId: 'G-K3H6XJCH92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh9vuGjyWcxrk3U9Ibwe1KSb2RIwjRvrE',
    appId: '1:159024373084:android:b1c3d353c7cd6d26113599',
    messagingSenderId: '159024373084',
    projectId: 'moappfinal-98952',
    storageBucket: 'moappfinal-98952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgFNs5kyK-3gG-pbGmtrm1mp2mkI_AwCQ',
    appId: '1:159024373084:ios:a0cf68173b07cc1d113599',
    messagingSenderId: '159024373084',
    projectId: 'moappfinal-98952',
    storageBucket: 'moappfinal-98952.firebasestorage.app',
    iosClientId: '159024373084-9kaarbakji3hb2iva9cbnfvdgoqlegd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgFNs5kyK-3gG-pbGmtrm1mp2mkI_AwCQ',
    appId: '1:159024373084:ios:a0cf68173b07cc1d113599',
    messagingSenderId: '159024373084',
    projectId: 'moappfinal-98952',
    storageBucket: 'moappfinal-98952.firebasestorage.app',
    iosClientId: '159024373084-9kaarbakji3hb2iva9cbnfvdgoqlegd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ZLXwRpGaMYM65oj726PhO1duyFdB8r0',
    appId: '1:159024373084:web:8498503c2126b7ce113599',
    messagingSenderId: '159024373084',
    projectId: 'moappfinal-98952',
    authDomain: 'moappfinal-98952.firebaseapp.com',
    storageBucket: 'moappfinal-98952.firebasestorage.app',
    measurementId: 'G-EGREZ18BHX',
  );

}